### ISSUE TITLE
error on installation - both windows and mac os platform

### ISSUE THREAD

**Issue by Hessel2333** [Alwinator/aw-watcher-utilization#18]
Hi, I did all the installation following your instructions, but it seems Module aw-watcher-utilization is not found

Here is the aw-qt log
"
2024-01-03 18:10:56 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2024-01-03 18:10:56 [WARNING]: Found matching file but was not executable: C:\Users\hessel\AppData\Local\Programs\ActivityWatch\aw-qt.desktop  (aw_qt.manager:64)
2024-01-03 18:10:56 [WARNING]: Found matching file but was not executable: C:\Users\hessel\AppData\Local\Programs\ActivityWatch\aw-server-rust\aw-server.service  (aw_qt.manager:64)
2024-01-03 18:10:56 [INFO ]: Found 7 bundled modules  (aw_qt.manager:85)
2024-01-03 18:10:56 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2024-01-03 18:10:56 [ERROR]: Module aw-watcher-utilization not found  (aw_qt.manager:273)
2024-01-03 18:10:56 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2024-01-03 18:10:56 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2024-01-03 18:10:56 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2024-01-03 18:10:56 [ERROR]: Manager tried to start nonexistent module aw-watcher-utilization  (aw_qt.manager:265)
2024-01-03 18:10:56 [INFO ]: Creating trayicon...  (aw_qt.trayicon:206)
2024-01-03 18:10:56 [INFO ]: Initialized aw-qt and trayicon successfully  (aw_qt.trayicon:262)
"

How should I check where is the problem?

**Comment by Alwinator** [comment]
Did you follow the installation section? https://github.com/Alwinator/aw-watcher-utilization?tab=readme-ov-file#installing

**Comment by Hessel2333** [comment]
Yes, I followed it step by step.
![Snipaste_2024-01-16_10-00-57](https://github.com/Alwinator/aw-watcher-utilization/assets/31088294/262c9bd9-49ec-4f8b-a9ab-999b95b8c398)
![Snipaste_2024-01-16_10-01-35](https://github.com/Alwinator/aw-watcher-utilization/assets/31088294/5c276277-35b4-4124-8aa6-be7ee18cf306)
![Snipaste_2024-01-16_10-02-05](https://github.com/Alwinator/aw-watcher-utilization/assets/31088294/73241e39-9f47-4a45-87ac-9c9838f8f93d)
![Snipaste_2024-01-16_10-02-42](https://github.com/Alwinator/aw-watcher-utilization/assets/31088294/2ab67dd5-c235-4b83-9529-153f785e9a61)

**Comment by Alwinator** [comment]
Can you please provide the detailed error message (to the code 400). How can see it by going to the Developer Options in your browser and then click on Console.

**Comment by Hessel2333** [comment]
error message is listed below:

<img width="538" alt="image" src="https://github.com/Alwinator/aw-watcher-utilization/assets/31088294/ae2cc6d3-d469-42fd-806d-b6122ac56e93">


xl-content.js:1  Uncaught (in promise) TypeError: Cannot read properties of null (reading '2')
    at xl-content.js:1:126721
(anonymous) @ xl-content.js:1

App.vue:1  [BootstrapVue warn]: BFormSelect - Setting prop "options" to an object is deprecated. Use the array format instead.
he @ warn.js:14
normalizeOptions @ form-options.js:61
formOptions @ form-options.js:25
t.get @ vue.runtime.esm.js:3446
t.evaluate @ vue.runtime.esm.js:3547
(anonymous) @ vue.runtime.esm.js:5537
render @ form-select.js:93
t._render @ vue.runtime.esm.js:2684
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
$n @ vue.runtime.esm.js:3892
no.$mount @ vue.runtime.esm.js:8772
init @ vue.runtime.esm.js:4407
v @ vue.runtime.esm.js:6567
p @ vue.runtime.esm.js:6521
w @ vue.runtime.esm.js:6640
p @ vue.runtime.esm.js:6544
w @ vue.runtime.esm.js:6640
p @ vue.runtime.esm.js:6544
w @ vue.runtime.esm.js:6640
p @ vue.runtime.esm.js:6544
w @ vue.runtime.esm.js:6640
p @ vue.runtime.esm.js:6544
(anonymous) @ vue.runtime.esm.js:7071
Mn.t._update @ vue.runtime.esm.js:3765
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
$n @ vue.runtime.esm.js:3892
no.$mount @ vue.runtime.esm.js:8772
init @ vue.runtime.esm.js:4407
r @ vue.runtime.esm.js:4561
v @ vue.runtime.esm.js:6567
p @ vue.runtime.esm.js:6521
w @ vue.runtime.esm.js:6640
p @ vue.runtime.esm.js:6544
(anonymous) @ vue.runtime.esm.js:7071
Mn.t._update @ vue.runtime.esm.js:3765
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
$n @ vue.runtime.esm.js:3892
no.$mount @ vue.runtime.esm.js:8772
init @ vue.runtime.esm.js:4407
v @ vue.runtime.esm.js:6567
p @ vue.runtime.esm.js:6521
P @ vue.runtime.esm.js:6816
D @ vue.runtime.esm.js:6909
P @ vue.runtime.esm.js:6783
D @ vue.runtime.esm.js:6909
P @ vue.runtime.esm.js:6783
D @ vue.runtime.esm.js:6909
(anonymous) @ vue.runtime.esm.js:7077
Mn.t._update @ vue.runtime.esm.js:3769
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
Xn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Wr @ vue.runtime.esm.js:3065
Promise.then(异步)
Hr @ vue.runtime.esm.js:3090
Jr @ vue.runtime.esm.js:3155
ri @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
Mn.t.$forceUpdate @ vue.runtime.esm.js:3794
l @ vue.runtime.esm.js:2761
(anonymous) @ vue.runtime.esm.js:2781
(anonymous) @ vue.runtime.esm.js:305
Promise.then(异步)
Cr @ vue.runtime.esm.js:2801
di @ vue.runtime.esm.js:4474
Mr @ vue.runtime.esm.js:2916
Ir @ vue.runtime.esm.js:2866
Tr.t._c @ vue.runtime.esm.js:2635
b @ App.vue:1
t._render @ vue.runtime.esm.js:2684
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
Xn @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Wr @ vue.runtime.esm.js:3065
Promise.then(异步)
Hr @ vue.runtime.esm.js:3090
Jr @ vue.runtime.esm.js:3155
ri @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
Ni.Li.set @ vue.runtime.esm.js:5356
(anonymous) @ App.vue:48
d @ regeneratorRuntime.js:45
(anonymous) @ regeneratorRuntime.js:133
(anonymous) @ regeneratorRuntime.js:74
n @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then(异步)
n @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
beforeCreate @ App.vue:34
Fr @ vue.runtime.esm.js:3017
Bn @ vue.runtime.esm.js:4031
Qi.t._init @ vue.runtime.esm.js:5689
a @ vue.runtime.esm.js:5826
pi @ vue.runtime.esm.js:4544
init @ vue.runtime.esm.js:4406
v @ vue.runtime.esm.js:6567
p @ vue.runtime.esm.js:6521
(anonymous) @ vue.runtime.esm.js:7109
Mn.t._update @ vue.runtime.esm.js:3765
n @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
$n @ vue.runtime.esm.js:3892
no.$mount @ vue.runtime.esm.js:8772
Qi.t._init @ vue.runtime.esm.js:5701
no @ vue.runtime.esm.js:5762
19132 @ main.js:83
n @ bootstrap:19
(anonymous) @ startup:4
n.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ index.3709e717.js:1

views.ts:104 Loaded views: (4) [{…}, {…}, {…}, {…}, __ob__: t]
activity.ts:235 Query options:  {timeperiod: {…}, host: 'Tians-MacBook-Air.local', force: undefined, filter_afk: true, include_audible: true, …}always_active_pattern: (...)filter_afk: (...)filter_categories: (...)force: (...)host: (...)include_audible: (...)include_stopwatch: (...)timeperiod: (...)__ob__: t {value: {…}, shallow: false, mock: false, dep: t, vmCount: 0}get always_active_pattern: ƒ ()set always_active_pattern: ƒ (e)get filter_afk: ƒ ()set filter_afk: ƒ (e)get filter_categories: ƒ ()set filter_categories: ƒ (e)get force: ƒ ()set force: ƒ (e)get host: ƒ ()set host: ƒ (e)get include_audible: ƒ ()set include_audible: ƒ (e)get include_stopwatch: ƒ ()set include_stopwatch: ƒ (e)get timeperiod: ƒ ()set timeperiod: ƒ (e)[[Prototype]]: Object
activity.ts:572 Available buckets:  {…}
activity.ts:252 Querying a single device
UncategorizedNotification.vue:22 null
xl-content.js:1  Uncaught (in promise) TypeError: Cannot read properties of null (reading '2')
    at xl-content.js:1:126721
(anonymous) @ xl-content.js:1

xhr.js:251 
        
        
        POST http://localhost:5600/api/0/query/ 400 (BAD REQUEST)
(anonymous) @ xhr.js:251
xhr @ xhr.js:49
Re @ dispatchRequest.js:51
value @ Axios.js:146
(anonymous) @ Axios.js:185
(anonymous) @ bind.js:5
(anonymous) @ aw-client.js:44
(anonymous) @ aw-client.js:8
__awaiter @ aw-client.js:4
_post @ aw-client.js:42
(anonymous) @ aw-client.js:233
(anonymous) @ aw-client.js:8
__awaiter @ aw-client.js:4
query @ aw-client.js:224
(anonymous) @ aw-watcher-utilization/?hostname=Tians-MacBook-Air.local&start=2024-01-17T04%3A00%3A00%2B08%3A00&end=2024-01-17T20%3A00%3A00.000Z&title=test:62
UncategorizedNotification.vue:22 (2) [8.246, 8066.295999999999]0: 8.2461: 8066.295999999999length: 2[[Prototype]]: Array(0)
activity.ts:292 Cannot call query_editor as we do not have any editor buckets

**Comment by Alwinator** [comment]
On which port and URL are you running activity watch?

**Comment by 4hmedHisham** [comment]
Hello, I'm Having the same problem 
![image](https://github.com/Alwinator/aw-watcher-utilization/assets/43798851/cf1207d6-d09f-490d-add0-0cb813a3f115)
![image](https://github.com/Alwinator/aw-watcher-utilization/assets/43798851/886897f8-3565-40cf-92f6-052142fdd7a1)
![image](https://github.com/Alwinator/aw-watcher-utilization/assets/43798851/f7f0f3fb-108f-4b27-9207-9c49009ad8de)




```
App.vue:1 [BootstrapVue warn]: BFormSelect - Setting prop "options" to an object is deprecated. Use the array format instead.
he @ warn.js:14
normalizeOptions @ form-options.js:61
formOptions @ form-options.js:25
t.get @ vue.runtime.esm.js:3407
t.evaluate @ vue.runtime.esm.js:3508
(anonymous) @ vue.runtime.esm.js:5479
render @ form-select.js:93
t._render @ vue.runtime.esm.js:2655
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t @ vue.runtime.esm.js:3397
Ar @ vue.runtime.esm.js:3848
to.$mount @ vue.runtime.esm.js:8704
init @ vue.runtime.esm.js:4362
v @ vue.runtime.esm.js:6508
p @ vue.runtime.esm.js:6462
w @ vue.runtime.esm.js:6581
p @ vue.runtime.esm.js:6485
w @ vue.runtime.esm.js:6581
p @ vue.runtime.esm.js:6485
w @ vue.runtime.esm.js:6581
p @ vue.runtime.esm.js:6485
w @ vue.runtime.esm.js:6581
p @ vue.runtime.esm.js:6485
(anonymous) @ vue.runtime.esm.js:7012
Er.t._update @ vue.runtime.esm.js:3726
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t @ vue.runtime.esm.js:3397
Ar @ vue.runtime.esm.js:3848
to.$mount @ vue.runtime.esm.js:8704
init @ vue.runtime.esm.js:4362
n @ vue.runtime.esm.js:4516
v @ vue.runtime.esm.js:6508
p @ vue.runtime.esm.js:6462
w @ vue.runtime.esm.js:6581
p @ vue.runtime.esm.js:6485
(anonymous) @ vue.runtime.esm.js:7012
Er.t._update @ vue.runtime.esm.js:3726
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t @ vue.runtime.esm.js:3397
Ar @ vue.runtime.esm.js:3848
to.$mount @ vue.runtime.esm.js:8704
init @ vue.runtime.esm.js:4362
v @ vue.runtime.esm.js:6508
p @ vue.runtime.esm.js:6462
P @ vue.runtime.esm.js:6757
D @ vue.runtime.esm.js:6850
P @ vue.runtime.esm.js:6724
D @ vue.runtime.esm.js:6850
P @ vue.runtime.esm.js:6724
D @ vue.runtime.esm.js:6850
(anonymous) @ vue.runtime.esm.js:7018
Er.t._update @ vue.runtime.esm.js:3730
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t.run @ vue.runtime.esm.js:3483
Zr @ vue.runtime.esm.js:4077
(anonymous) @ vue.runtime.esm.js:3114
Yn @ vue.runtime.esm.js:3036
Promise.then (async)
Vn @ vue.runtime.esm.js:3061
Kn @ vue.runtime.esm.js:3126
Qr @ vue.runtime.esm.js:4162
t.update @ vue.runtime.esm.js:3474
Er.t.$forceUpdate @ vue.runtime.esm.js:3750
l @ vue.runtime.esm.js:2732
(anonymous) @ vue.runtime.esm.js:2752
(anonymous) @ vue.runtime.esm.js:299
Promise.then (async)
Pn @ vue.runtime.esm.js:2772
li @ vue.runtime.esm.js:4429
In @ vue.runtime.esm.js:2887
An @ vue.runtime.esm.js:2837
t._c @ vue.runtime.esm.js:2606
b @ App.vue:1
t._render @ vue.runtime.esm.js:2655
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t @ vue.runtime.esm.js:3397
Ar @ vue.runtime.esm.js:3848
to.$mount @ vue.runtime.esm.js:8704
init @ vue.runtime.esm.js:4362
v @ vue.runtime.esm.js:6508
p @ vue.runtime.esm.js:6462
(anonymous) @ vue.runtime.esm.js:7050
Er.t._update @ vue.runtime.esm.js:3726
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t @ vue.runtime.esm.js:3397
Ar @ vue.runtime.esm.js:3848
to.$mount @ vue.runtime.esm.js:8704
Ki.t._init @ vue.runtime.esm.js:5642
to @ vue.runtime.esm.js:5703
27470 @ main.js:76
n @ bootstrap:19
(anonymous) @ startup:4
n.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ index.ec88f1bc.js:1
Show 92 more frames
Show less
views.ts:104 Loaded views: (5) [{…}, {…}, {…}, {…}, {…}, __ob__: t]0: {__ob__: t}elements: (...)id: (...)name: (...)__ob__: t {value: {…}, shallow: false, mock: false, dep: t, vmCount: 0}get elements: ƒ ()set elements: ƒ (e)get id: ƒ ()set id: ƒ (e)get name: ƒ ()set name: ƒ (e)[[Prototype]]: Object1: {__ob__: t}2: {__ob__: t}3: {__ob__: t}4: {__ob__: t}length: 5__ob__: t {value: Array(5), shallow: false, mock: false, dep: t, vmCount: 0}[[Prototype]]: Array
activity.ts:227 Query options:  {timeperiod: {…}, host: 'justpc', force: undefined, filter_afk: true, include_audible: true, …}
activity.ts:533 Available buckets:  {…}afk: (...)android: (...)browser: (...)editor: (...)loaded: (...)stopwatch: (...)window: (...)__ob__: t {value: {…}, shallow: false, mock: false, dep: t, vmCount: 0}get afk: ƒ ()set afk: ƒ (e)get android: ƒ ()set android: ƒ (e)get browser: ƒ ()set browser: ƒ (e)get editor: ƒ ()set editor: ƒ (e)get loaded: ƒ ()set loaded: ƒ (e)get stopwatch: ƒ ()set stopwatch: ƒ (e)get window: ƒ ()set window: ƒ (e)[[Prototype]]: Object
activity.ts:244 Querying a single device
UncategorizedNotification.vue:22 null
activity.ts:208 (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: t]0: {__ob__: t}1: {__ob__: t}2: {__ob__: t}3: {__ob__: t}4: {__ob__: t}5: {__ob__: t}6: {__ob__: t}length: 7__ob__: t {value: Array(7), shallow: false, mock: false, dep: t, vmCount: 0}[[Prototype]]: Array
UncategorizedNotification.vue:22 (2) [762.765, 2899.348]0: 762.7651: 2899.348length: 2[[Prototype]]: Array(0)
activity.ts:284 Cannot call query_editor as we do not have any editor buckets
vue.runtime.esm.js:6248 
        
        
       GET http://localhost:5600/pages/aw-watcher-utilization/?hostname=justpc&start=2024-04-13T04%3A00%3A00%2B02%3A00&end=2024-04-14T02%3A00%3A00.000Z 404 (NOT FOUND)
Go @ vue.runtime.esm.js:6248
b @ vue.runtime.esm.js:6567
v @ vue.runtime.esm.js:6516
p @ vue.runtime.esm.js:6462
P @ vue.runtime.esm.js:6757
D @ vue.runtime.esm.js:6850
P @ vue.runtime.esm.js:6724
D @ vue.runtime.esm.js:6850
P @ vue.runtime.esm.js:6724
D @ vue.runtime.esm.js:6850
(anonymous) @ vue.runtime.esm.js:7018
Er.t._update @ vue.runtime.esm.js:3730
r @ vue.runtime.esm.js:3831
t.get @ vue.runtime.esm.js:3407
t.run @ vue.runtime.esm.js:3483
Zr @ vue.runtime.esm.js:4077
(anonymous) @ vue.runtime.esm.js:3114
Yn @ vue.runtime.esm.js:3036
Promise.then (async)
Vn @ vue.runtime.esm.js:3061
Kn @ vue.runtime.esm.js:3126
Qr @ vue.runtime.esm.js:4162
t.update @ vue.runtime.esm.js:3474
Er.t.$forceUpdate @ vue.runtime.esm.js:3750
l @ vue.runtime.esm.js:2732
(anonymous) @ vue.runtime.esm.js:2752
(anonymous) @ vue.runtime.esm.js:299
Show 26 more frames
Show less

```
I'm using the default port and im not sure what do you mean by URL

**Comment by ragul-n** [comment]
Have you managed to fix it? I am also facing the same issue in M2 mac.

**Comment by specula** [comment]
I had this issue on Windows after following the installation instructions, where the example installation dir is `\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization`.
Instead I had to place the watcher in `Users\<USER>\AppData\Local\Programs\ActivityWatch`.

Also as I am using `aw-server-rust` to get the custom visualization working I had to add to its `config.toml` file:
```
[custom_static]
aw-watcher-utilization = '''\Users\<USER>\AppData\Local\Programs\ActivityWatch\aw-watcher-utilization\visualization'''
```

**Comment by Hiallthejetbrains** [comment]
I am also experiencing this issue, and am wondering if the directory that we all seem to be placing it in on Mac is incorrect. Maybe it should go somewhere else?

**Comment by johnemau** [comment]
It is not clear to me from the instruction which directory I should place the unarchived folder in.
> Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows: C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization

Can you also provide the example for macOS?

**Comment by johnemau** [comment]
> It is not clear to me from the instruction which directory I should place the unarchived folder in.
> 
> > Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows: C:\Users<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization
> 
> Can you also provide the example for macOS?

I answered my own question based on the screenshots provided by @Hessel2333.

Since I installed the ActivityWatch with the dmg file download and NOT homebrew, my folder is `/Users/<USER NAME>/Library/Application Support/activitywatch/<aw-watcher-utilization>` goes here

**Comment by johnemau** [comment]
> > It is not clear to me from the instruction which directory I should place the unarchived folder in.
> > > Move the folder to the directly ActivityWatch is installed (depends on your setup). For example, on Windows: C:\Users\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization
> > 
> > 
> > Can you also provide the example for macOS?
> 
> I answered my own question based on the screenshots provided by [@Hessel2333](https://github.com/Hessel2333).
> 
> Since I installed the ActivityWatch with the dmg file download and NOT homebrew, my folder is `/Users/<USER NAME>/Library/Application Support/activitywatch/<aw-watcher-utilization>` goes here

I am hitting similar issues now- I have everything setup correctly but `aw-watcher-utilization` does not appear to be recognized as a module (although I am not getting any errors).

**Comment by Hiallthejetbrains** [comment]
Hey, just wanted to comment on this! For my aw-utilization install, I placed it in `<your-aw-qt-app-path>/Contents/MacOS` (to see the Contents, right click on the app and click "Show Package Contents"). I copied the folder into it (in my case the path was `Applications/ActivityWatch.app/Contents/MacOS`) and deleted the ini file inside the aw-watcher-utilization folder, as it creates an issue in the search code that AW uses.
